### ISSUE TITLE
Field validation does not work with final-form v4+

### ISSUE THREAD

**Issue by visualfanatic** [egoist/vue-final-form#3]
@egoist I love the work you did with this package, thank you!

Since `v4.0.0` of `final-form`, it is using `getValidator` instead of `validate` when registering a new field, additionaly it has to return a function that returns the validation function. Unfortunately, that means the last working version of `final-form` is `3.1.0`.

Here is the PR with the change:
final-form/final-form#58

**Comment by egoist** [comment]
Thanks for letting me know, mind sending a PR to fix this?

**Comment by visualfanatic** [comment]
Done in #4 👍
